import BaseCard from "@/components/ui/BaseCard";
import Button from "@/components/ui/Button";
import PlaybookLink from "@/components/playbooks/PlaybookLink";
import { suggestionForMilestone } from "./missionSuggestions";
import { getPlaybookForMission } from "@/lib/playbooks/resourceMap";

// Phase 10.6 -- Idea Lab V2, Part 9. "Your next 3 moves" -- the EXACT
// SAME deterministic, rule-based `next_milestones` list
// app/ai/vps_guidance.py's generate_guidance() already computes (already
// prioritized toward the venture's largest uncertainties -- see that
// module's own _next_milestones(), unchanged), just sliced to 3 and given
// a more prominent, focused presentation than the old "Next Milestones"
// card buried at the bottom of the page. Nothing here is generated by
// this component; a longer list from the same source remains available
// via VPSResultPanel's own Next Milestones section.
//
// Phase 10.7, Part 5: `onMakeMission` is optional and additive -- when a
// caller supplies it, each item gets a "Make this a mission" action.
// NextMoves itself never creates anything; it only reports which
// milestone text the founder chose. The founder always chooses --
// nothing here is auto-converted into a mission.
type NextMovesProps = {
  milestones: string[];
  onMakeMission?: (milestoneText: string) => void;
  missionedMilestones?: string[];
};

export default function NextMoves({ milestones, onMakeMission, missionedMilestones = [] }: NextMovesProps) {
  if (milestones.length === 0) {
    return null;
  }

  const topThree = milestones.slice(0, 3);

  return (
    <BaseCard variant="raised" className="p-6">
      <p className="text-xs font-semibold uppercase tracking-wide text-text-muted">
        Your next {topThree.length === 1 ? "move" : `${topThree.length} moves`}
      </p>

      <ol className="mt-3 space-y-3">
        {topThree.map((milestone, index) => {
          const alreadyMissioned = missionedMilestones.includes(milestone);
          const suggestion = suggestionForMilestone(milestone);
          // Phase 14 -- Founder Journey Audit, Part 11: resolves through
          // getPlaybookForMission (the SAME function MissionsSection uses
          // for the actual, created Mission), not the coarser
          // category-only getPlaybookForVpsCategory this used to call --
          // that mismatch was the concrete, confirmed bug this phase
          // found: a milestone could show one "Learn how" playbook here,
          // then a DIFFERENT one once turned into a Mission (e.g.
          // "Secure a first paying customer..." showed Customer Discovery
          // here but a different -- or, before Phase 12's mission_type
          // fix, still-wrong -- playbook once missioned). Passing the
          // full suggestion (missionType + relatedCategory) guarantees
          // this list and the Mission card it feeds always agree, by
          // construction, for every milestone -- not patched one string
          // at a time.
          const playbook = getPlaybookForMission(suggestion);

          return (
            <li key={milestone} className="flex items-start gap-3">
              <span className="flex size-6 shrink-0 items-center justify-center rounded-full bg-primary-soft text-xs font-bold text-primary">
                {index + 1}
              </span>
              <div className="flex-1 pt-0.5">
                <p className="text-sm leading-6 text-text-primary">{milestone}</p>

                <div className="mt-1 flex flex-wrap items-center gap-x-3 gap-y-1">
                  {onMakeMission ? (
                    <Button
                      type="button"
                      variant="subtle"
                      size="sm"
                      className="-ml-3.5"
                      disabled={alreadyMissioned}
                      onClick={() => onMakeMission(milestone)}
                    >
                      {alreadyMissioned ? "Added to your actions ✓" : "Make this an action →"}
                    </Button>
                  ) : null}

                  {playbook ? <PlaybookLink slug={playbook.slug} label={`Learn how: ${playbook.title} →`} /> : null}
                </div>
              </div>
            </li>
          );
        })}
      </ol>

      <p className="mt-4 text-xs text-text-muted">
        These reduce the venture&rsquo;s biggest unknowns first — not guarantees of success.
      </p>
    </BaseCard>
  );
}
