import BaseCard from "@/components/ui/BaseCard";

// Phase 10.6 -- Idea Lab V2, Part 9. "Your next 3 moves" -- the EXACT
// SAME deterministic, rule-based `next_milestones` list
// app/ai/vps_guidance.py's generate_guidance() already computes (already
// prioritized toward the venture's largest uncertainties -- see that
// module's own _next_milestones(), unchanged), just sliced to 3 and given
// a more prominent, focused presentation than the old "Next Milestones"
// card buried at the bottom of the page. Nothing here is generated by
// this component; a longer list from the same source remains available
// via VPSResultPanel's own Next Milestones section.
type NextMovesProps = {
  milestones: string[];
};

export default function NextMoves({ milestones }: NextMovesProps) {
  if (milestones.length === 0) {
    return null;
  }

  const topThree = milestones.slice(0, 3);

  return (
    <BaseCard variant="raised" className="p-6">
      <p className="text-xs font-semibold uppercase tracking-wide text-text-muted">
        Your next {topThree.length === 1 ? "move" : `${topThree.length} moves`}
      </p>

      <ol className="mt-3 space-y-3">
        {topThree.map((milestone, index) => (
          <li key={milestone} className="flex items-start gap-3">
            <span className="flex size-6 shrink-0 items-center justify-center rounded-full bg-primary-soft text-xs font-bold text-primary">
              {index + 1}
            </span>
            <span className="pt-0.5 text-sm leading-6 text-text-primary">{milestone}</span>
          </li>
        ))}
      </ol>

      <p className="mt-4 text-xs text-text-muted">
        These reduce the venture&rsquo;s biggest unknowns first — not guarantees of success.
      </p>
    </BaseCard>
  );
}
