from dataclasses import dataclass


@dataclass(frozen=True)
class ScoringDimension:
    name: str
    weight: float
    question: str
    description: str
    stage_guidance: str
    score_9_10: str
    score_7_8: str
    score_5_6: str
    score_3_4: str
    score_0_2: str
    strong_signals: list[str]
    weak_signals: list[str]
    diligence_questions: list[str]


SCORING_METHODOLOGY = {
    "Market": [
        ScoringDimension(
            name="Market Size",
            weight=0.25,
            question="How large is the realistic addressable market if this company executes successfully?",
            description="Evaluate venture-scale market potential. Do not punish missing TAM alone.",
            stage_guidance="Pre-seed: infer from problem and ICP. Seed: expect early market validation. Series A: expect credible expansion path. Series B+: expect proof of category scale.",
            score_9_10="Massive global market with multiple expansion paths and multi-billion-dollar outcome potential.",
            score_7_8="Large attractive market with meaningful expansion potential.",
            score_5_6="Moderate market with some expansion uncertainty.",
            score_3_4="Limited market or constrained growth ceiling.",
            score_0_2="Tiny niche with little venture-scale upside.",
            strong_signals=["Large enterprise market", "Global opportunity", "Multiple segments", "Expansion potential", "Secular tailwinds"],
            weak_signals=["Tiny niche", "Local-only market", "Limited expansion", "Shrinking demand"],
            diligence_questions=["What is TAM/SAM/SOM?", "What adjacent markets exist?", "Can this become venture-scale?"],
        ),
        ScoringDimension(
            name="Market Growth",
            weight=0.20,
            question="Is the underlying market growing rapidly?",
            description="Evaluate category growth, not just company growth.",
            stage_guidance="Pre-seed: look for emerging tailwinds. Seed: look for buyer urgency. Series A: expect clear category expansion. Series B+: expect durable growth.",
            score_9_10="Rapidly expanding market with strong secular tailwinds.",
            score_7_8="Healthy growing market with clear demand drivers.",
            score_5_6="Stable or moderately growing market.",
            score_3_4="Slow-growth market.",
            score_0_2="Declining market.",
            strong_signals=["AI adoption", "Digital transformation", "Regulatory tailwinds", "Budget growth", "Urgent buyer pain"],
            weak_signals=["Shrinking budgets", "Declining demand", "Stagnant category", "No growth driver"],
            diligence_questions=["What is driving growth?", "Are budgets increasing?", "Is growth durable?"],
        ),
        ScoringDimension(
            name="Market Timing",
            weight=0.20,
            question="Is now the right time for this solution?",
            description="Evaluate whether customers, technology, and budgets are ready now.",
            stage_guidance="Pre-seed: timing may be thesis-driven. Seed: expect early urgency. Series A: expect adoption momentum. Series B+: timing should already be validated.",
            score_9_10="Excellent timing with urgent demand and strong market pull.",
            score_7_8="Good timing supported by adoption trends.",
            score_5_6="Acceptable timing but requires education.",
            score_3_4="Premature, late, or unclear timing.",
            score_0_2="Poor timing with little adoption readiness.",
            strong_signals=["Customer urgency", "Technology inflection", "Regulatory change", "Budget availability", "Acute pain"],
            weak_signals=["Low urgency", "Customers not ready", "Premature market", "Late commodity market"],
            diligence_questions=["Why now?", "What changed?", "Are buyers actively searching?"],
        ),
        ScoringDimension(
            name="Competitive Intensity",
            weight=0.15,
            question="Can the company realistically win despite competition?",
            description="Do not punish competition alone. Evaluate wedge, differentiation, and right to win.",
            stage_guidance="Pre-seed: expect credible wedge. Seed: expect early differentiation. Series A: expect wedge working. Series B+: expect durable position.",
            score_9_10="Clear wedge, durable differentiation, and credible path to category leadership.",
            score_7_8="Differentiated with manageable competition.",
            score_5_6="Some differentiation but unclear durability.",
            score_3_4="Crowded market with limited differentiation.",
            score_0_2="Commodity product with no credible path to win.",
            strong_signals=["Clear wedge", "Switching costs", "Workflow lock-in", "Distribution advantage", "Unique insight"],
            weak_signals=["Commodity offering", "No wedge", "Powerful incumbents", "Feature parity"],
            diligence_questions=["Why will this company win?", "What prevents copying?", "What is the wedge?"],
        ),
        ScoringDimension(
            name="Customer Demand",
            weight=0.20,
            question="Is there evidence customers genuinely want this product?",
            description="Evaluate pull through adoption, revenue, retention, expansion, and customer outcomes.",
            stage_guidance="Pre-seed: discovery/LOIs may count. Seed: expect pilots or early customers. Series A: expect repeatable demand. Series B+: expect scalable demand.",
            score_9_10="Exceptional demand with rapid adoption, retention, expansion, and pull.",
            score_7_8="Strong demand with paying customers and validation.",
            score_5_6="Some validation but still emerging.",
            score_3_4="Limited validation or weak urgency.",
            score_0_2="Little or no customer demand.",
            strong_signals=["Paying customers", "Revenue growth", "High retention", "Expansion revenue", "Case studies", "Strong usage"],
            weak_signals=["No customers", "Weak retention", "Low usage", "Unclear pain"],
            diligence_questions=["Are customers pulling the product?", "What retention exists?", "How urgent is the pain?"],
        ),
    ],

    "Team": [
        ScoringDimension(
            name="Founder-Market Fit",
            weight=0.25,
            question="Does the founding team have unusually strong insight or experience in the market?",
            description="Evaluate founder connection to the customer, problem, and industry.",
            stage_guidance="Pre-seed: this is one of the most important signals. Seed: expect customer insight. Series A+: expect founder-market fit to show in execution.",
            score_9_10="Exceptional founder-market fit with direct domain expertise and strong prior success.",
            score_7_8="Strong fit with relevant experience.",
            score_5_6="Some relevant experience but not clearly advantaged.",
            score_3_4="Limited relevant experience.",
            score_0_2="No clear connection to the market.",
            strong_signals=["Former buyer", "Domain expert", "Repeat founder", "Prior exit", "Deep customer knowledge"],
            weak_signals=["No domain expertise", "Generic background", "Weak customer insight"],
            diligence_questions=["Why this team?", "What customer insight do they have?", "Have they built in this market before?"],
        ),
        ScoringDimension(
            name="Technical Capability",
            weight=0.20,
            question="Can the team build and maintain the product?",
            description="Evaluate technical capability relative to product complexity.",
            stage_guidance="Pre-seed: technical founder matters. Seed: expect MVP/product execution. Series A+: expect scalable engineering capability.",
            score_9_10="Exceptional technical capability with proof of complex product execution.",
            score_7_8="Strong technical capability.",
            score_5_6="Adequate capability with scaling risk.",
            score_3_4="Weak technical depth.",
            score_0_2="No credible ability to build the product.",
            strong_signals=["Technical founder", "Complex product built", "Deep integrations", "AI expertise", "Infrastructure expertise"],
            weak_signals=["No technical founder", "Outsourced core product", "Unproven technical claims"],
            diligence_questions=["Who owns technical architecture?", "Can the product scale?", "What is proprietary?"],
        ),
        ScoringDimension(
            name="Business Capability",
            weight=0.20,
            question="Can the team sell, operate, and build a real company?",
            description="Evaluate commercial, operational, and company-building capability.",
            stage_guidance="Pre-seed: expect commercial instincts. Seed: expect early GTM learning. Series A+: expect repeatable business execution.",
            score_9_10="Exceptional commercial execution and operating discipline.",
            score_7_8="Strong business capability.",
            score_5_6="Some business capability with gaps.",
            score_3_4="Limited business execution.",
            score_0_2="No evidence of commercial capability.",
            strong_signals=["Revenue growth", "Repeatable sales", "Strong unit economics", "Enterprise acquisition", "Prior scaling"],
            weak_signals=["No GTM clarity", "Weak sales", "Poor economics", "No operating discipline"],
            diligence_questions=["Who owns sales?", "Is GTM repeatable?", "Can the team scale operations?"],
        ),
        ScoringDimension(
            name="Leadership",
            weight=0.20,
            question="Can the team lead, hire, and scale the organization?",
            description="Evaluate leadership maturity, hiring ability, and team-building.",
            stage_guidance="Pre-seed: founder leadership matters. Seed: expect early hiring. Series A+: expect executive scaling capability.",
            score_9_10="Exceptional leadership with proven organization-building ability.",
            score_7_8="Strong leadership indicators.",
            score_5_6="Moderate leadership evidence.",
            score_3_4="Limited leadership evidence.",
            score_0_2="No evidence of leadership capacity.",
            strong_signals=["Prior leadership", "Hiring success", "Executive team", "Company-building experience"],
            weak_signals=["No leadership detail", "Founder conflict", "Weak hiring", "No structure"],
            diligence_questions=["Can they hire A-players?", "Who is missing from leadership?", "Can founders scale?"],
        ),
        ScoringDimension(
            name="Execution Track Record",
            weight=0.15,
            question="Has the team demonstrated the ability to execute?",
            description="Evaluate demonstrated progress against meaningful milestones.",
            stage_guidance="Pre-seed: execution can be prototype/discovery. Seed: expect early traction. Series A+: expect measurable growth and delivery.",
            score_9_10="Exceptional execution history with rapid progress and repeated milestone achievement.",
            score_7_8="Strong execution with clear progress.",
            score_5_6="Some execution evidence.",
            score_3_4="Weak or inconsistent execution.",
            score_0_2="Little or no execution evidence.",
            strong_signals=["Rapid growth", "Product shipped", "Customer adoption", "Fundraising progress", "Prior exit"],
            weak_signals=["Slow progress", "Missed milestones", "No product", "No traction"],
            diligence_questions=["What milestones were hit?", "How fast did they execute?", "What has slipped?"],
        ),
    ],

    "Product": [
        ScoringDimension(
            name="Customer Value",
            weight=0.25,
            question="Does the product solve an important customer problem?",
            description="Evaluate pain severity, ROI, and customer outcomes.",
            stage_guidance="Pre-seed: value can be qualitative. Seed: expect early proof. Series A+: expect measurable customer outcomes.",
            score_9_10="Exceptional customer value with urgent pain and measurable ROI.",
            score_7_8="Strong customer value.",
            score_5_6="Moderate value but not clearly mission-critical.",
            score_3_4="Weak value proposition.",
            score_0_2="No clear customer value.",
            strong_signals=["Measurable ROI", "High retention", "Urgent pain", "Mission-critical workflow", "Strong outcomes"],
            weak_signals=["Nice-to-have", "Weak ROI", "Unclear pain", "Low usage"],
            diligence_questions=["What ROI does the product deliver?", "Is it mission-critical?", "What happens if customers stop using it?"],
        ),
        ScoringDimension(
            name="Differentiation",
            weight=0.20,
            question="Is the product meaningfully different from alternatives?",
            description="Evaluate uniqueness, superiority, and wedge.",
            stage_guidance="Pre-seed: expect thesis-level differentiation. Seed: expect early proof. Series A+: expect differentiation customers recognize.",
            score_9_10="Highly differentiated with a clear durable wedge.",
            score_7_8="Meaningfully differentiated.",
            score_5_6="Some differentiation but easy to imitate.",
            score_3_4="Limited differentiation.",
            score_0_2="Undifferentiated commodity.",
            strong_signals=["Unique workflow", "Better outcomes", "AI advantage", "Domain insight", "Clear wedge"],
            weak_signals=["Feature parity", "No wedge", "Commodity positioning", "Similar competitors"],
            diligence_questions=["Why is this better?", "What do customers choose it over?", "Can competitors copy it?"],
        ),
        ScoringDimension(
            name="Usability",
            weight=0.15,
            question="Can customers adopt and use the product easily?",
            description="Evaluate onboarding, workflow fit, implementation, and UX.",
            stage_guidance="Pre-seed: usability can be early. Seed: expect usable MVP. Series A+: expect scalable onboarding.",
            score_9_10="Very easy adoption with excellent workflow fit.",
            score_7_8="Good usability and adoption experience.",
            score_5_6="Usable with some friction.",
            score_3_4="Difficult adoption.",
            score_0_2="Hard to use or unlikely to be adopted.",
            strong_signals=["Easy onboarding", "Workflow integration", "Low implementation burden", "Positive user feedback"],
            weak_signals=["Complex setup", "Long implementation", "Poor UX", "High training burden"],
            diligence_questions=["How long is implementation?", "Who uses it daily?", "What causes adoption friction?"],
        ),
        ScoringDimension(
            name="Defensibility",
            weight=0.20,
            question="Can the product become difficult to copy or replace?",
            description="Evaluate moats beyond patents: data, integrations, switching costs, ecosystem, distribution.",
            stage_guidance="Pre-seed: defensibility may be thesis-based. Seed: expect emerging wedge. Series A+: expect evidence of lock-in. Series B+: expect durable moat.",
            score_9_10="Very strong defensibility through multiple durable moats.",
            score_7_8="Strong defensibility through integrations, data, lock-in, or distribution.",
            score_5_6="Some defensibility but not durable yet.",
            score_3_4="Limited defensibility.",
            score_0_2="No defensibility.",
            strong_signals=["Switching costs", "Deep integrations", "Proprietary data", "Network effects", "Workflow lock-in", "Regulatory complexity"],
            weak_signals=["Easy to copy", "No switching costs", "No proprietary advantage", "No ecosystem position"],
            diligence_questions=["What is the moat?", "What gets stronger with scale?", "Why won't incumbents copy it?"],
        ),
        ScoringDimension(
            name="Adoption Potential",
            weight=0.20,
            question="Can adoption scale meaningfully?",
            description="Evaluate expansion potential across users, teams, accounts, and markets.",
            stage_guidance="Pre-seed: assess likely adoption path. Seed: expect early adoption. Series A+: expect repeatable adoption.",
            score_9_10="Exceptional adoption potential with strong pull and expansion paths.",
            score_7_8="Strong adoption potential.",
            score_5_6="Moderate adoption with friction.",
            score_3_4="Limited adoption potential.",
            score_0_2="Very low adoption potential.",
            strong_signals=["Repeatable sales", "Low churn", "Expansion revenue", "Enterprise adoption", "Multi-team usage"],
            weak_signals=["Long sales cycle", "Low usage", "Narrow use case", "Difficult onboarding"],
            diligence_questions=["Can this expand inside accounts?", "What limits adoption?", "Is sales repeatable?"],
        ),
    ],

    "Execution": [
        ScoringDimension(
            name="Go-to-Market Execution",
            weight=0.20,
            question="Is the company effectively acquiring customers?",
            description="Evaluate sales motion, ICP clarity, pipeline, acquisition efficiency, and repeatability.",
            stage_guidance="Pre-seed: GTM may be founder-led. Seed: expect GTM learning. Series A+: expect repeatability.",
            score_9_10="Exceptional GTM with rapid acquisition and repeatable motion.",
            score_7_8="Strong GTM execution.",
            score_5_6="Some GTM traction but not repeatable.",
            score_3_4="Weak GTM execution.",
            score_0_2="No evidence of customer acquisition.",
            strong_signals=["Repeatable sales", "Clear ICP", "Efficient CAC", "Strong pipeline", "Enterprise customers"],
            weak_signals=["No GTM clarity", "Weak pipeline", "High CAC", "Unclear buyer"],
            diligence_questions=["Is GTM repeatable?", "What is CAC by channel?", "How strong is pipeline?"],
        ),
        ScoringDimension(
            name="Product Execution",
            weight=0.20,
            question="Is the team executing well on product development?",
            description="Evaluate product maturity, roadmap delivery, quality, integrations, and reliability.",
            stage_guidance="Pre-seed: expect prototype. Seed: expect usable product. Series A+: expect mature product serving customers.",
            score_9_10="Exceptional product execution with mature product and strong outcomes.",
            score_7_8="Strong product execution.",
            score_5_6="Moderate product execution.",
            score_3_4="Weak product execution.",
            score_0_2="No credible product execution.",
            strong_signals=["Product shipped", "Deep integrations", "High reliability", "Strong outcomes", "Fast iteration"],
            weak_signals=["Immature product", "Quality issues", "Unclear roadmap", "Slow development"],
            diligence_questions=["What has shipped?", "What is roadmap velocity?", "How reliable is product?"],
        ),
        ScoringDimension(
            name="Operational Execution",
            weight=0.20,
            question="Can the company operate efficiently as it scales?",
            description="Evaluate burn, margin, hiring, processes, and scaling discipline.",
            stage_guidance="Pre-seed: lightweight ops acceptable. Seed: expect basic discipline. Series A+: expect scalable operating cadence.",
            score_9_10="Exceptional operating discipline and scalability.",
            score_7_8="Strong operating execution.",
            score_5_6="Adequate operations with scaling risk.",
            score_3_4="Weak operations.",
            score_0_2="Poor operating discipline.",
            strong_signals=["Efficient burn", "Healthy margins", "Strong runway", "Hiring plan", "Operational processes"],
            weak_signals=["High burn", "No operating discipline", "Weak hiring", "Process gaps"],
            diligence_questions=["Can operations scale?", "Is burn disciplined?", "What team/process gaps exist?"],
        ),
        ScoringDimension(
            name="Strategic Execution",
            weight=0.20,
            question="Is the company making strategically sound decisions?",
            description="Evaluate positioning, focus, sequencing, partnerships, and competitive response.",
            stage_guidance="Pre-seed: expect focused wedge. Seed: expect clear ICP. Series A+: expect coherent expansion strategy.",
            score_9_10="Exceptional strategic clarity and positioning.",
            score_7_8="Strong strategy with credible path to scale.",
            score_5_6="Reasonable strategy with unknowns.",
            score_3_4="Weak strategy.",
            score_0_2="No credible strategy.",
            strong_signals=["Clear wedge", "Strong positioning", "Logical expansion", "Strategic partnerships", "Competitive response"],
            weak_signals=["Unclear strategy", "Weak positioning", "No expansion logic", "Reactive decisions"],
            diligence_questions=["What is the wedge?", "What is the sequencing?", "How does strategy respond to competition?"],
        ),
        ScoringDimension(
            name="Execution Velocity",
            weight=0.20,
            question="Is the company moving fast enough?",
            description="Evaluate speed of revenue growth, customer acquisition, product delivery, and milestones.",
            stage_guidance="Pre-seed: velocity is learning/building. Seed: velocity is PMF progress. Series A+: velocity is growth and scaling.",
            score_9_10="Exceptional velocity with rapid growth and milestone achievement.",
            score_7_8="Strong velocity.",
            score_5_6="Moderate velocity.",
            score_3_4="Slow progress.",
            score_0_2="Stalled execution.",
            strong_signals=["Rapid MRR growth", "Fast customer acquisition", "Product velocity", "Hiring momentum", "Milestones hit"],
            weak_signals=["Flat growth", "Slow product progress", "Missed milestones", "Stalled GTM"],
            diligence_questions=["How fast is revenue growing?", "What milestones were hit?", "Where is execution slow?"],
        ),
    ],

    "Traction": [
        ScoringDimension(
            name="Customer Growth",
            weight=0.20,
            question="Is the customer base growing meaningfully?",
            description="Evaluate customer acquisition relative to stage, segment, and business model.",
            stage_guidance="Pre-seed: customers not required. Seed: expect pilots/early users. Series A+: expect meaningful customer base growth.",
            score_9_10="Exceptional customer growth with clear market pull.",
            score_7_8="Strong customer growth.",
            score_5_6="Moderate customer growth.",
            score_3_4="Weak customer growth.",
            score_0_2="Little or no customer growth.",
            strong_signals=["Growing customer count", "Enterprise adoption", "Repeatable acquisition", "Strong pipeline"],
            weak_signals=["No customers", "Flat customer count", "Weak acquisition", "Unclear pipeline"],
            diligence_questions=["How fast is customer count growing?", "What is customer quality?", "Is acquisition repeatable?"],
        ),
        ScoringDimension(
            name="Revenue Growth",
            weight=0.20,
            question="Is revenue growing strongly?",
            description="Evaluate growth rate relative to stage, sales motion, ACV, and market.",
            stage_guidance="Pre-seed: revenue optional. Seed: early revenue is strong signal. Series A+: expect repeatable revenue growth.",
            score_9_10="Exceptional revenue growth for the stage.",
            score_7_8="Strong revenue growth.",
            score_5_6="Moderate revenue growth.",
            score_3_4="Weak revenue growth.",
            score_0_2="No revenue or declining revenue.",
            strong_signals=["Rapid MRR growth", "ARR expansion", "Strong ACV", "Expansion revenue"],
            weak_signals=["No revenue", "Flat revenue", "Declining revenue", "Weak monetization"],
            diligence_questions=["What is YoY growth?", "Is growth new logo or expansion?", "Is revenue durable?"],
        ),
        ScoringDimension(
            name="Retention",
            weight=0.20,
            question="Are customers staying and expanding?",
            description="Evaluate churn, NRR, GRR, renewals, and expansion.",
            stage_guidance="Pre-seed: retention may be unavailable. Seed: early retention matters. Series A+: retention is critical.",
            score_9_10="Exceptional retention and expansion with very low churn.",
            score_7_8="Strong retention.",
            score_5_6="Moderate retention.",
            score_3_4="Weak retention or concerning churn.",
            score_0_2="Severe churn or no retention evidence.",
            strong_signals=["High NRR", "High GRR", "Low churn", "Renewals", "Expansion revenue"],
            weak_signals=["High churn", "Weak retention", "No renewals", "Low expansion"],
            diligence_questions=["What is NRR?", "What is GRR?", "Why do customers churn?"],
        ),
        ScoringDimension(
            name="Engagement",
            weight=0.20,
            question="Are customers actively using the product?",
            description="Evaluate usage frequency, workflow volume, depth, and product stickiness.",
            stage_guidance="Pre-seed: qualitative engagement may count. Seed: expect usage signal. Series A+: expect measurable engagement.",
            score_9_10="Exceptional usage depth and frequency.",
            score_7_8="Strong engagement.",
            score_5_6="Some engagement evidence but incomplete.",
            score_3_4="Weak usage.",
            score_0_2="Little or no engagement evidence.",
            strong_signals=["High usage", "Workflow volume", "Active users", "Deep workflow adoption", "Customer outcome data"],
            weak_signals=["No usage metrics", "Low activity", "Shallow usage", "Weak stickiness"],
            diligence_questions=["How often is product used?", "How deep is workflow adoption?", "What usage predicts retention?"],
        ),
        ScoringDimension(
            name="Commercial Validation",
            weight=0.20,
            question="Is there convincing commercial proof?",
            description="Evaluate paying customers, renewals, expansion, pricing power, and customer proof.",
            stage_guidance="Pre-seed: commercial validation may be LOIs. Seed: expect early paid proof. Series A+: expect strong commercial evidence.",
            score_9_10="Exceptional commercial validation with strong revenue, retention, economics, and proof.",
            score_7_8="Strong commercial validation.",
            score_5_6="Some commercial proof but early.",
            score_3_4="Limited commercial validation.",
            score_0_2="No commercial validation.",
            strong_signals=["Paying customers", "Strong ACV", "Good unit economics", "Case studies", "Expansion revenue"],
            weak_signals=["No paying customers", "No renewals", "Weak pricing", "No customer proof"],
            diligence_questions=["Are customers paying real money?", "Is pricing sustainable?", "Do customers renew and expand?"],
        ),
    ],

    "Financial Health": [
        ScoringDimension(
            name="Revenue Quality",
            weight=0.20,
            question="Is revenue durable, recurring, and high quality?",
            description="Evaluate recurring revenue, retention, predictability, concentration, and customer quality.",
            stage_guidance="Pre-seed: revenue optional. Seed: quality may be early. Series A+: revenue quality matters heavily.",
            score_9_10="Exceptional recurring revenue quality with strong retention and predictability.",
            score_7_8="Strong revenue quality.",
            score_5_6="Moderate revenue quality.",
            score_3_4="Weak revenue quality.",
            score_0_2="No meaningful or poor-quality revenue.",
            strong_signals=["Recurring revenue", "High NRR", "Low churn", "Enterprise customers", "Predictable contracts"],
            weak_signals=["One-time revenue", "High churn", "Concentration risk", "Unclear contracts"],
            diligence_questions=["Is revenue recurring?", "How concentrated is revenue?", "What is renewal quality?"],
        ),
        ScoringDimension(
            name="Unit Economics",
            weight=0.20,
            question="Are the economics of acquiring and serving customers attractive?",
            description="Evaluate gross margin, CAC payback, LTV:CAC, pricing power, and efficiency.",
            stage_guidance="Pre-seed: may be unknown. Seed: early signals. Series A+: expect credible unit economics.",
            score_9_10="Exceptional unit economics with high margin, fast payback, and strong LTV:CAC.",
            score_7_8="Strong unit economics.",
            score_5_6="Acceptable economics with uncertainty.",
            score_3_4="Weak unit economics.",
            score_0_2="Unsustainable economics.",
            strong_signals=["High gross margin", "Fast CAC payback", "Strong LTV:CAC", "Efficient sales", "Expansion revenue"],
            weak_signals=["Low margin", "Long CAC payback", "Poor LTV:CAC", "Unclear pricing"],
            diligence_questions=["What is CAC payback?", "What is LTV:CAC?", "Do economics hold as sales scale?"],
        ),
        ScoringDimension(
            name="Burn Efficiency",
            weight=0.20,
            question="Is the company using capital efficiently?",
            description="Evaluate burn relative to revenue, growth, stage, and milestones.",
            stage_guidance="Pre-seed: burn should be controlled. Seed: spend should create learning. Series A+: burn should map to growth.",
            score_9_10="Exceptional capital efficiency with strong growth relative to spend.",
            score_7_8="Good burn efficiency.",
            score_5_6="Moderate burn efficiency.",
            score_3_4="Concerning burn efficiency.",
            score_0_2="Severe burn problem.",
            strong_signals=["Revenue exceeds burn", "Efficient growth", "Disciplined spend", "Strong margin", "Clear use of capital"],
            weak_signals=["High burn", "Weak growth relative to spend", "No spend discipline", "Unclear capital plan"],
            diligence_questions=["What is burn multiple?", "How does spend map to growth?", "Can burn be reduced if needed?"],
        ),
        ScoringDimension(
            name="Runway",
            weight=0.20,
            question="Does the company have enough cash runway?",
            description="Evaluate runway relative to fundraising needs, growth plan, and stage.",
            stage_guidance="Pre-seed/Seed: runway should support next milestone. Series A+: runway should support scaling and next raise.",
            score_9_10="Excellent runway with strong flexibility.",
            score_7_8="Healthy runway.",
            score_5_6="Adequate runway but fundraising timing matters.",
            score_3_4="Short runway or fundraising pressure.",
            score_0_2="Critical runway risk.",
            strong_signals=["18+ months runway", "Strong cash position", "Controlled burn", "Clear fundraising plan"],
            weak_signals=["Short runway", "High burn", "Unclear financing", "Immediate cash risk"],
            diligence_questions=["How many months runway?", "What milestone will cash reach?", "When is next raise needed?"],
        ),
        ScoringDimension(
            name="Fundraising Readiness",
            weight=0.20,
            question="Is the company well positioned to raise capital?",
            description="Evaluate whether traction, team, market, metrics, and narrative support the next financing.",
            stage_guidance="Pre-seed: team/thesis matter. Seed: early proof matters. Series A+: metrics and repeatability matter. Series B+: scale and efficiency matter.",
            score_9_10="Exceptional fundraising profile likely to attract strong investor interest.",
            score_7_8="Strong fundraising readiness.",
            score_5_6="Some readiness but gaps remain.",
            score_3_4="Weak fundraising profile.",
            score_0_2="Not ready for institutional capital.",
            strong_signals=["Strong growth", "Strong retention", "Experienced founders", "Healthy economics", "Large market", "Clear use of funds"],
            weak_signals=["Weak metrics", "Unclear market", "Poor economics", "No narrative", "Short runway"],
            diligence_questions=["Why fund this now?", "What milestones will capital unlock?", "What investor objections remain?"],
        ),
    ],
}