from dataclasses import dataclass


@dataclass(frozen=True)
class ScoringDimension:
    name: str
    weight: float
    question: str
    description: str
    score_9_10: str
    score_7_8: str
    score_5_6: str
    score_3_4: str
    score_0_2: str
    strong_signals: list[str]
    weak_signals: list[str]


SCORING_METHODOLOGY = {
    "Market": [
        ScoringDimension(
            name="Market Size",
            weight=0.25,
            question="How large is the realistic addressable market if this company executes successfully?",
            description=(
                "Evaluate the long-term economic opportunity. Do not reduce the score simply because TAM is not explicitly stated. "
                "Infer market size from customers, industry, product, and business model when appropriate."
            ),
            score_9_10="Massive global market with multiple expansion opportunities and potential for multi-billion-dollar outcomes.",
            score_7_8="Large attractive market with meaningful long-term growth potential.",
            score_5_6="Reasonably sized market with moderate expansion opportunities.",
            score_3_4="Limited addressable market or constrained long-term growth.",
            score_0_2="Very small niche with little opportunity for venture-scale returns.",
            strong_signals=[
                "Large enterprise market",
                "Global opportunity",
                "Multiple customer segments",
                "Large TAM",
                "Strong secular trends",
            ],
            weak_signals=[
                "Single local market",
                "Tiny niche",
                "Limited expansion",
                "Shrinking demand",
            ],
        ),
        ScoringDimension(
            name="Market Growth",
            weight=0.20,
            question="Is the underlying market growing rapidly?",
            description=(
                "Evaluate whether the category has strong secular growth. Company revenue growth can support demand, "
                "but market growth should reflect broader category expansion."
            ),
            score_9_10="Rapidly expanding category with strong secular tailwinds and accelerating adoption.",
            score_7_8="Healthy growing market with clear demand drivers.",
            score_5_6="Stable or moderately growing market.",
            score_3_4="Slow-growth market with weak expansion signals.",
            score_0_2="Declining market or shrinking category.",
            strong_signals=[
                "AI adoption",
                "Digital transformation",
                "Regulatory tailwinds",
                "Increasing budget allocation",
                "Growing buyer urgency",
            ],
            weak_signals=[
                "Declining demand",
                "Shrinking budgets",
                "No clear growth driver",
                "Stagnant category",
            ],
        ),
        ScoringDimension(
            name="Market Timing",
            weight=0.20,
            question="Is now the right time for this solution?",
            description="Evaluate whether customer readiness, technology maturity, and market conditions favor adoption now.",
            score_9_10="Excellent timing with strong customer urgency, technology readiness, and market pull.",
            score_7_8="Good timing supported by adoption trends and customer demand.",
            score_5_6="Acceptable timing but adoption may still require education or market development.",
            score_3_4="Timing appears premature, late, or misaligned with buyer readiness.",
            score_0_2="Poor timing with little evidence that customers are ready to adopt.",
            strong_signals=[
                "Customer urgency",
                "Technology inflection point",
                "Regulatory change",
                "Budget availability",
                "Pain point becoming acute",
            ],
            weak_signals=[
                "Premature market",
                "Low buyer urgency",
                "Customers not ready",
                "Late commodity market",
            ],
        ),
        ScoringDimension(
            name="Competitive Intensity",
            weight=0.15,
            question="Can the company realistically win despite competition?",
            description=(
                "Do not punish a startup simply because competitors exist. Evaluate whether the company has a credible wedge, "
                "differentiation, positioning, or unfair advantage."
            ),
            score_9_10="Strong competitive position with clear wedge, durable differentiation, and credible path to category leadership.",
            score_7_8="Differentiated with manageable competition and a credible right to win.",
            score_5_6="Competitive market with some differentiation but unclear durability.",
            score_3_4="Highly competitive market with limited differentiation.",
            score_0_2="Commodity offering with no credible differentiation or path to win.",
            strong_signals=[
                "Clear wedge",
                "Strong differentiation",
                "Switching costs",
                "Workflow lock-in",
                "Unique positioning",
                "Founder insight",
                "Distribution advantage",
            ],
            weak_signals=[
                "Commodity product",
                "Undifferentiated competitors",
                "Incumbents with overwhelming advantage",
                "No clear wedge",
            ],
        ),
        ScoringDimension(
            name="Customer Demand",
            weight=0.20,
            question="Is there evidence customers genuinely want this product?",
            description="Evaluate customer pull using adoption, revenue, retention, expansion, and customer outcomes.",
            score_9_10="Exceptional demand shown by rapid adoption, strong retention, expansion, and clear customer pull.",
            score_7_8="Strong demand with paying customers and meaningful validation.",
            score_5_6="Some validation, but demand is still emerging.",
            score_3_4="Limited validation or weak customer urgency.",
            score_0_2="Little or no evidence customers want the product.",
            strong_signals=[
                "Paying customers",
                "Revenue growth",
                "High retention",
                "Expansion revenue",
                "Customer case studies",
                "Strong usage",
            ],
            weak_signals=[
                "No customers",
                "No validation",
                "Weak retention",
                "Low usage",
                "Unclear buyer pain",
            ],
        ),
    ],

    "Team": [
        ScoringDimension(
            name="Founder-Market Fit",
            weight=0.25,
            question="Does the founding team have unusually strong insight or experience in the market?",
            description="Evaluate whether the founders understand the customer, problem, and market deeply.",
            score_9_10="Exceptional founder-market fit with direct domain expertise, customer insight, and relevant prior success.",
            score_7_8="Strong fit with relevant experience and credible market understanding.",
            score_5_6="Some relevant experience but not clearly advantaged.",
            score_3_4="Limited relevant experience or weak market understanding.",
            score_0_2="No clear connection between the team and the problem.",
            strong_signals=[
                "Direct industry experience",
                "Repeat founder",
                "Prior successful exit",
                "Deep customer knowledge",
                "Former buyer or operator in the market",
            ],
            weak_signals=[
                "No domain expertise",
                "No customer insight",
                "Generic founder background",
                "Weak problem understanding",
            ],
        ),
        ScoringDimension(
            name="Technical Capability",
            weight=0.20,
            question="Can the team build and maintain the product?",
            description="Evaluate engineering, product, AI, infrastructure, or technical ability relative to product complexity.",
            score_9_10="Exceptional technical capability with proven ability to build complex systems.",
            score_7_8="Strong technical team with credible execution ability.",
            score_5_6="Adequate technical capability but some scaling or complexity risk.",
            score_3_4="Weak technical depth relative to product requirements.",
            score_0_2="No evidence the team can build the product.",
            strong_signals=[
                "Experienced technical founder",
                "Complex product already built",
                "Deep integrations",
                "AI or infrastructure expertise",
                "Strong engineering background",
            ],
            weak_signals=[
                "No technical founder",
                "Outsourced core product",
                "Unproven technical claims",
                "Weak product maturity",
            ],
        ),
        ScoringDimension(
            name="Business Capability",
            weight=0.20,
            question="Can the team sell, operate, and build a real company?",
            description="Evaluate GTM, sales, finance, operations, and business-building capability.",
            score_9_10="Exceptional business capability with strong GTM execution, capital efficiency, and scaling evidence.",
            score_7_8="Strong business capability with good commercial execution.",
            score_5_6="Some business capability but gaps remain.",
            score_3_4="Limited business execution evidence.",
            score_0_2="No evidence of commercial or operational capability.",
            strong_signals=[
                "Revenue growth",
                "Repeatable sales motion",
                "Strong unit economics",
                "Enterprise customer acquisition",
                "Prior scaling experience",
            ],
            weak_signals=[
                "No GTM clarity",
                "No sales capability",
                "Weak unit economics",
                "Poor operating discipline",
            ],
        ),
        ScoringDimension(
            name="Leadership",
            weight=0.20,
            question="Can the team lead, hire, and scale the organization?",
            description="Evaluate leadership maturity, team-building, hiring, and ability to navigate complexity.",
            score_9_10="Exceptional leadership with proven ability to scale teams and organizations.",
            score_7_8="Strong leadership indicators with credible scaling ability.",
            score_5_6="Moderate leadership evidence with some unknowns.",
            score_3_4="Limited leadership evidence or meaningful leadership gaps.",
            score_0_2="No evidence of leadership capacity.",
            strong_signals=[
                "Prior leadership roles",
                "Hiring success",
                "Organizational maturity",
                "Previous company-building",
                "Strong executive team",
            ],
            weak_signals=[
                "No leadership details",
                "Founder conflict",
                "Weak hiring ability",
                "No operating structure",
            ],
        ),
        ScoringDimension(
            name="Execution Track Record",
            weight=0.15,
            question="Has the team demonstrated the ability to execute?",
            description="Evaluate demonstrated progress, growth, product delivery, and milestone achievement.",
            score_9_10="Exceptional execution history with rapid progress and repeated milestone achievement.",
            score_7_8="Strong execution with clear evidence of progress.",
            score_5_6="Some execution evidence but incomplete track record.",
            score_3_4="Weak or inconsistent execution.",
            score_0_2="Little or no execution evidence.",
            strong_signals=[
                "Rapid revenue growth",
                "Product shipped",
                "Customer adoption",
                "Fundraising progress",
                "Previous exit",
            ],
            weak_signals=[
                "Slow progress",
                "Missed milestones",
                "No product shipped",
                "No customer traction",
            ],
        ),
    ],

    "Product": [
        ScoringDimension(
            name="Customer Value",
            weight=0.25,
            question="Does the product solve an important customer problem?",
            description="Evaluate pain severity, customer outcomes, ROI, and measurable value.",
            score_9_10="Exceptional customer value with clear ROI, urgent pain, and strong customer outcomes.",
            score_7_8="Strong customer value with meaningful impact.",
            score_5_6="Moderate value but not clearly mission-critical.",
            score_3_4="Weak value proposition or unclear customer benefit.",
            score_0_2="No clear customer value.",
            strong_signals=[
                "Measurable ROI",
                "High retention",
                "Strong customer outcomes",
                "Urgent workflow pain",
                "Mission-critical use case",
            ],
            weak_signals=[
                "Nice-to-have product",
                "Weak ROI",
                "Unclear pain",
                "Low usage",
            ],
        ),
        ScoringDimension(
            name="Differentiation",
            weight=0.20,
            question="Is the product meaningfully different from alternatives?",
            description="Evaluate product uniqueness, customer wedge, and superiority versus alternatives.",
            score_9_10="Highly differentiated product with a clear and durable wedge.",
            score_7_8="Meaningfully differentiated with strong positioning.",
            score_5_6="Some differentiation but risk of imitation or commoditization.",
            score_3_4="Limited differentiation.",
            score_0_2="Undifferentiated commodity product.",
            strong_signals=[
                "Unique workflow",
                "Better outcomes",
                "AI advantage",
                "Deep domain insight",
                "Clear wedge",
            ],
            weak_signals=[
                "Similar to competitors",
                "No clear wedge",
                "Feature parity",
                "Commodity positioning",
            ],
        ),
        ScoringDimension(
            name="Usability",
            weight=0.15,
            question="Can customers adopt and use the product easily?",
            description="Evaluate ease of adoption, implementation, onboarding, and workflow fit.",
            score_9_10="Extremely easy adoption with strong workflow fit and low friction.",
            score_7_8="Good usability and adoption experience.",
            score_5_6="Usable but with onboarding or implementation friction.",
            score_3_4="Difficult adoption or high customer friction.",
            score_0_2="Product is hard to use or unlikely to be adopted.",
            strong_signals=[
                "Easy onboarding",
                "Workflow integration",
                "Low implementation burden",
                "Strong user feedback",
            ],
            weak_signals=[
                "Complex setup",
                "Long implementation",
                "Poor UX",
                "High training burden",
            ],
        ),
        ScoringDimension(
            name="Defensibility",
            weight=0.20,
            question="Can the product become difficult to copy or replace?",
            description="Do not equate defensibility only with patents. Evaluate switching costs, data, integrations, workflow lock-in, distribution, and ecosystem position.",
            score_9_10="Very strong defensibility through multiple durable moats.",
            score_7_8="Strong defensibility through integrations, data, workflow lock-in, or distribution.",
            score_5_6="Some defensibility but not yet durable.",
            score_3_4="Limited defensibility and easy to copy.",
            score_0_2="No defensibility.",
            strong_signals=[
                "Switching costs",
                "Deep integrations",
                "Proprietary data",
                "Network effects",
                "Workflow lock-in",
                "Regulatory complexity",
                "Distribution advantage",
            ],
            weak_signals=[
                "Easy to copy",
                "No switching costs",
                "No proprietary advantage",
                "No ecosystem position",
            ],
        ),
        ScoringDimension(
            name="Adoption Potential",
            weight=0.20,
            question="Can adoption scale meaningfully?",
            description="Evaluate whether the product can spread across customers, teams, accounts, or markets.",
            score_9_10="Exceptional adoption potential with strong pull and scalable expansion paths.",
            score_7_8="Strong adoption potential with credible scaling motion.",
            score_5_6="Moderate adoption potential with some friction.",
            score_3_4="Limited adoption potential due to friction or narrow use case.",
            score_0_2="Very low adoption potential.",
            strong_signals=[
                "Repeatable sales motion",
                "Low churn",
                "Expansion revenue",
                "Enterprise adoption",
                "Multi-seat or multi-team use",
            ],
            weak_signals=[
                "Long sales cycle",
                "Low usage",
                "Narrow use case",
                "Difficult onboarding",
            ],
        ),
    ],

    "Execution": [
        ScoringDimension(
            name="Go-to-Market Execution",
            weight=0.20,
            question="Is the company effectively acquiring customers?",
            description="Evaluate sales motion, channel strategy, pipeline, customer acquisition, and conversion.",
            score_9_10="Exceptional GTM execution with rapid customer acquisition and repeatable sales motion.",
            score_7_8="Strong GTM execution with credible repeatability.",
            score_5_6="Some GTM traction but not fully repeatable.",
            score_3_4="Weak GTM execution or unclear sales motion.",
            score_0_2="No evidence of customer acquisition ability.",
            strong_signals=[
                "Repeatable sales motion",
                "Enterprise customers",
                "Efficient CAC",
                "Strong pipeline",
                "Clear ICP",
            ],
            weak_signals=[
                "No GTM clarity",
                "Weak pipeline",
                "High CAC",
                "Unclear buyer",
            ],
        ),
        ScoringDimension(
            name="Product Execution",
            weight=0.20,
            question="Is the team executing well on product development?",
            description="Evaluate product maturity, roadmap delivery, quality, integrations, and customer outcomes.",
            score_9_10="Exceptional product execution with mature product and strong customer outcomes.",
            score_7_8="Strong product execution with credible maturity.",
            score_5_6="Moderate product execution with remaining gaps.",
            score_3_4="Weak product execution.",
            score_0_2="No credible product execution.",
            strong_signals=[
                "Product shipped",
                "Deep integrations",
                "High reliability",
                "Strong customer outcomes",
                "Fast iteration",
            ],
            weak_signals=[
                "Immature product",
                "Unclear roadmap",
                "Quality issues",
                "Slow development",
            ],
        ),
        ScoringDimension(
            name="Operational Execution",
            weight=0.20,
            question="Can the company operate efficiently as it scales?",
            description="Evaluate operating discipline, burn, process maturity, hiring, and ability to manage growth.",
            score_9_10="Exceptional operating discipline and scalability.",
            score_7_8="Strong operating execution with healthy discipline.",
            score_5_6="Adequate operations but some scaling risk.",
            score_3_4="Weak operations or inefficient scaling.",
            score_0_2="Poor operating discipline.",
            strong_signals=[
                "Efficient burn",
                "Healthy margins",
                "Clear hiring plan",
                "Operational processes",
                "Strong runway",
            ],
            weak_signals=[
                "High burn",
                "No operating discipline",
                "Weak hiring plan",
                "Process gaps",
            ],
        ),
        ScoringDimension(
            name="Strategic Execution",
            weight=0.20,
            question="Is the company making strategically sound decisions?",
            description="Evaluate positioning, market entry, expansion plan, partnerships, and competitive strategy.",
            score_9_10="Exceptional strategic clarity and positioning.",
            score_7_8="Strong strategy with credible path to scale.",
            score_5_6="Reasonable strategy but important unknowns remain.",
            score_3_4="Weak strategy or unclear positioning.",
            score_0_2="No credible strategy.",
            strong_signals=[
                "Clear wedge",
                "Strong positioning",
                "Strategic partnerships",
                "Logical expansion plan",
                "Competitive response",
            ],
            weak_signals=[
                "Unclear strategy",
                "Weak positioning",
                "No expansion logic",
                "Reactive decisions",
            ],
        ),
        ScoringDimension(
            name="Execution Velocity",
            weight=0.20,
            question="Is the company moving fast enough?",
            description="Evaluate speed of revenue growth, product progress, customer acquisition, and milestone achievement relative to stage.",
            score_9_10="Exceptional velocity with rapid growth and milestone achievement.",
            score_7_8="Strong velocity for the company’s stage.",
            score_5_6="Moderate velocity.",
            score_3_4="Slow progress relative to stage.",
            score_0_2="Very slow or stalled execution.",
            strong_signals=[
                "Rapid MRR growth",
                "Fast customer acquisition",
                "Product velocity",
                "Hiring momentum",
                "Milestone progress",
            ],
            weak_signals=[
                "Flat growth",
                "Slow product progress",
                "Missed milestones",
                "Stalled GTM",
            ],
        ),
    ],

    "Traction": [
        ScoringDimension(
            name="Customer Growth",
            weight=0.20,
            question="Is the customer base growing meaningfully?",
            description="Evaluate customer acquisition relative to stage, segment, and business model.",
            score_9_10="Exceptional customer growth with clear market pull.",
            score_7_8="Strong customer growth for the stage.",
            score_5_6="Moderate customer growth.",
            score_3_4="Weak customer growth.",
            score_0_2="Little or no customer growth.",
            strong_signals=[
                "Growing customer count",
                "Enterprise adoption",
                "Repeatable acquisition",
                "Strong pipeline",
            ],
            weak_signals=[
                "No customers",
                "Flat customer count",
                "Weak acquisition",
                "Unclear pipeline",
            ],
        ),
        ScoringDimension(
            name="Revenue Growth",
            weight=0.20,
            question="Is revenue growing strongly?",
            description="Evaluate growth rate relative to stage, ACV, market, and sales motion.",
            score_9_10="Exceptional revenue growth for the stage.",
            score_7_8="Strong revenue growth.",
            score_5_6="Moderate revenue growth.",
            score_3_4="Weak revenue growth.",
            score_0_2="No revenue or declining revenue.",
            strong_signals=[
                "Rapid MRR growth",
                "ARR expansion",
                "Strong ACV",
                "Expansion revenue",
            ],
            weak_signals=[
                "No revenue",
                "Flat revenue",
                "Declining revenue",
                "Weak monetization",
            ],
        ),
        ScoringDimension(
            name="Retention",
            weight=0.20,
            question="Are customers staying and expanding?",
            description="Evaluate retention, churn, expansion, stickiness, and customer satisfaction.",
            score_9_10="Exceptional retention and expansion with very low churn.",
            score_7_8="Strong retention and customer stickiness.",
            score_5_6="Moderate retention with some churn risk.",
            score_3_4="Weak retention or concerning churn.",
            score_0_2="Severe churn or no retention evidence.",
            strong_signals=[
                "High NRR",
                "High GRR",
                "Low churn",
                "Expansion revenue",
                "Renewals",
            ],
            weak_signals=[
                "High churn",
                "Low retention",
                "No renewal data",
                "Weak expansion",
            ],
        ),
        ScoringDimension(
            name="Engagement",
            weight=0.20,
            question="Are customers actively using the product?",
            description="Evaluate product usage, workflow depth, automation volume, frequency, and engagement quality.",
            score_9_10="Exceptional usage depth and frequency.",
            score_7_8="Strong engagement with meaningful usage.",
            score_5_6="Some engagement evidence but incomplete metrics.",
            score_3_4="Weak usage or shallow engagement.",
            score_0_2="Little or no engagement evidence.",
            strong_signals=[
                "High usage frequency",
                "Workflow volume",
                "Active users",
                "Customer outcome data",
                "Deep workflow adoption",
            ],
            weak_signals=[
                "No usage metrics",
                "Low activity",
                "Shallow usage",
                "Weak product stickiness",
            ],
        ),
        ScoringDimension(
            name="Commercial Validation",
            weight=0.20,
            question="Is there convincing commercial proof?",
            description="Evaluate whether customers are paying, renewing, expanding, and achieving value.",
            score_9_10="Exceptional commercial validation with strong revenue, retention, unit economics, and customer proof.",
            score_7_8="Strong commercial validation.",
            score_5_6="Some commercial proof but still early.",
            score_3_4="Limited commercial validation.",
            score_0_2="No commercial validation.",
            strong_signals=[
                "Paying customers",
                "Strong ACV",
                "Good unit economics",
                "Case studies",
                "Expansion revenue",
            ],
            weak_signals=[
                "No paying customers",
                "No renewals",
                "Weak pricing",
                "No customer proof",
            ],
        ),
    ],

    "Financial Health": [
        ScoringDimension(
            name="Revenue Quality",
            weight=0.20,
            question="Is revenue durable, recurring, and high quality?",
            description="Evaluate recurring revenue, retention, concentration, predictability, and customer quality.",
            score_9_10="Exceptional revenue quality with strong recurring revenue, retention, and predictability.",
            score_7_8="Strong revenue quality.",
            score_5_6="Moderate revenue quality with some risks.",
            score_3_4="Weak or low-quality revenue.",
            score_0_2="No meaningful revenue or poor-quality revenue.",
            strong_signals=[
                "Recurring revenue",
                "High NRR",
                "Low churn",
                "Enterprise customers",
                "Predictable contracts",
            ],
            weak_signals=[
                "One-time revenue",
                "High churn",
                "Concentration risk",
                "Unclear contracts",
            ],
        ),
        ScoringDimension(
            name="Unit Economics",
            weight=0.20,
            question="Are the economics of acquiring and serving customers attractive?",
            description="Evaluate CAC payback, LTV:CAC, gross margin, pricing, and efficiency.",
            score_9_10="Exceptional unit economics with high margin, fast payback, and strong LTV:CAC.",
            score_7_8="Strong unit economics.",
            score_5_6="Acceptable unit economics with some uncertainty.",
            score_3_4="Weak unit economics.",
            score_0_2="Unsustainable unit economics.",
            strong_signals=[
                "High gross margin",
                "Fast CAC payback",
                "Strong LTV:CAC",
                "Efficient sales motion",
                "Expansion revenue",
            ],
            weak_signals=[
                "Low margin",
                "Long CAC payback",
                "Poor LTV:CAC",
                "Unclear pricing",
            ],
        ),
        ScoringDimension(
            name="Burn Efficiency",
            weight=0.20,
            question="Is the company using capital efficiently?",
            description="Evaluate burn relative to revenue, growth, runway, and stage.",
            score_9_10="Exceptional burn efficiency with strong growth relative to spend.",
            score_7_8="Good burn efficiency.",
            score_5_6="Moderate burn efficiency.",
            score_3_4="Inefficient burn or concerning spend.",
            score_0_2="Severe burn problem.",
            strong_signals=[
                "Revenue exceeds burn",
                "Efficient growth",
                "Disciplined spend",
                "Strong margin",
                "Clear use of capital",
            ],
            weak_signals=[
                "High burn",
                "Weak growth relative to spend",
                "No spend discipline",
                "Unclear capital plan",
            ],
        ),
        ScoringDimension(
            name="Runway",
            weight=0.20,
            question="Does the company have enough cash runway?",
            description="Evaluate cash runway relative to stage, fundraising needs, and growth plan.",
            score_9_10="Excellent runway with strong flexibility.",
            score_7_8="Healthy runway.",
            score_5_6="Adequate runway but fundraising timing matters.",
            score_3_4="Short runway or fundraising pressure.",
            score_0_2="Critical runway risk.",
            strong_signals=[
                "18+ months runway",
                "Strong cash position",
                "Controlled burn",
                "Clear fundraising plan",
            ],
            weak_signals=[
                "Short runway",
                "High burn",
                "Unclear financing",
                "Immediate cash risk",
            ],
        ),
        ScoringDimension(
            name="Fundraising Readiness",
            weight=0.20,
            question="Is the company well positioned to raise capital?",
            description="Evaluate whether traction, team, market, metrics, and narrative support the next financing milestone.",
            score_9_10="Exceptional fundraising profile likely to attract strong investor interest.",
            score_7_8="Strong fundraising readiness with credible metrics and narrative.",
            score_5_6="Some fundraising readiness but important gaps remain.",
            score_3_4="Weak fundraising profile.",
            score_0_2="Not ready to raise institutional capital.",
            strong_signals=[
                "Strong growth",
                "Strong retention",
                "Experienced founders",
                "Healthy unit economics",
                "Clear use of funds",
                "Large market",
            ],
            weak_signals=[
                "Weak metrics",
                "Unclear market",
                "No investor narrative",
                "Poor unit economics",
                "Short runway",
            ],
        ),
    ],
}