import type { Playbook } from "./types.ts";

// Phase 10.9 -- Founder Playbooks V1, Part 3. Eleven required playbooks
// plus one small bonus piece (Part 7). Written for someone who has never
// founded a company before -- plain English over jargon, short sections
// over textbook chapters. Every "why it matters" sentence explains an
// idea, never claims to predict this specific founder's outcome.
export const PLAYBOOKS: Playbook[] = [
  {
    slug: "customer-discovery",
    title: "Customer Discovery",
    description: "How to talk to real people before you build anything.",
    journeyStage: "start",
    audience: "founder",
    estimatedMinutes: 6,
    relatedPlaybooks: ["problem-validation", "mvp", "pricing-validation"],
    whatIsThis: [
      "Customer discovery is the practice of talking directly to the people you think have the problem you want to solve, before you spend time or money building a solution.",
      "It's not a sales pitch and it's not a survey about your idea. It's a conversation about their life, their workflow, or their frustrations — with your idea barely mentioned.",
    ],
    whyItMatters: "Most failed startups don't fail because the product was built badly. They fail because nobody actually wanted it. A handful of honest conversations early on is the cheapest way to find that out before you've invested months building something.",
    steps: [
      "List 10-20 people who plausibly have the problem you're interested in — not friends and family who will just be nice to you.",
      "Ask for 15-20 minutes to learn about how they currently handle the situation, not to pitch them anything.",
      "Ask about their past behavior and specific recent examples, not hypothetical future behavior (\"Tell me about the last time this happened\" beats \"Would you use an app for this?\").",
      "Let them talk more than you do. Silence is fine — resist the urge to fill it by explaining your idea.",
      "Write down what you heard right after each conversation, while it's fresh.",
      "Look for patterns across conversations, not conclusions from any single one.",
    ],
    commonMistakes: [
      "Describing your solution and asking \"would you use this?\" — almost everyone says yes to be polite.",
      "Only talking to people who already agree with you.",
      "Treating one enthusiastic conversation as proof, or one lukewarm one as failure.",
      "Asking about the future (\"would you pay for X\") instead of the past (\"what did you do last time\").",
    ],
    checklist: [
      "You have talked to at least 10-15 people outside your existing network.",
      "You asked about their past behavior, not their predicted future behavior.",
      "You wrote down notes after each conversation.",
      "You can describe a real, specific example a real person gave you — not a paraphrase of your own idea.",
      "You've noticed at least one pattern across multiple conversations.",
    ],
    whatGoodLooksLike: "You can repeat back a specific story a stranger told you about their problem, in their own words — not your pitch reflected back at you.",
    objective: "Learn whether the problem you think people have is one they actually, currently experience — in their own words, not yours.",
    beforeYouStart: [
      "Pick a specific type of person, not \"anyone who might use this\" — e.g. \"ops managers at 20-50 person logistics companies,\" not \"business owners.\"",
      "Find 10-20 of them through your own network's edges, relevant online communities, LinkedIn search, or a niche forum — not just people who already like you.",
      "Reach out with a short, honest ask: you're researching the space, not selling anything, and you want 15-20 minutes to learn how they currently handle something.",
      "Block real time for each conversation and for writing notes right after — a rushed interview or a forgotten write-up loses most of the value.",
    ],
    questionsToAskOrDo: [
      "\"Walk me through the last time [the problem] came up. What were you doing right before?\"",
      "\"What did you do about it? Who else was involved?\"",
      "\"How did you end up handling it in the end?\"",
      "\"What did that cost you — in time, money, or something else?\"",
      "\"How often does this come up?\"",
      "\"What have you already tried to fix this? What happened?\"",
      "\"If you had a magic wand, what would you change about how this works today?\" (only near the end, if at all)",
    ],
    exampleScript: [
      { speaker: "You", line: "Thanks for making time. I'm not here to sell you anything — I'm trying to understand how teams like yours currently handle scheduling changes. Can you walk me through the last time a shift change came up?" },
      { speaker: "Them", line: "Sure — last Tuesday, actually. One of our drivers called in sick at 6am." },
      { speaker: "You", line: "What happened right after that call?" },
      { speaker: "Them", line: "I had to call around to three other drivers to see who could cover, then update the route sheet by hand." },
      { speaker: "You", line: "How long did that take, start to finish?" },
      { speaker: "Them", line: "Maybe 40 minutes, and I was late updating dispatch." },
      { speaker: "You", line: "Has that kind of thing happened before? How often?" },
      { speaker: "Them", line: "At least once a week, honestly." },
      { speaker: "You", line: "Have you tried anything to make that easier?" },
      { speaker: "Them", line: "We looked at a scheduling app once but it didn't handle our routes well, so we gave up on it." },
    ],
    goodSignal: [
      "They describe a specific, recent, real event with concrete details (who, when, what happened) without you prompting for specifics.",
      "They've already tried something — a tool, a workaround, a spreadsheet, hiring help — to deal with the problem themselves.",
      "They get visibly more animated or frustrated describing the problem, unprompted.",
      "The same underlying story shows up, in different words, across multiple unrelated interviews.",
    ],
    weakSignal: [
      "\"That's a great idea\" or \"I'd probably use that\" — a hypothetical reaction to your idea, not a report of their actual experience.",
      "Vague, generic answers with no specific example (\"yeah, that happens sometimes\") even after you ask for a recent instance.",
      "Enthusiasm only appears after you describe your solution, not while they were describing their situation.",
      "They can't recall the last time it actually happened when asked directly.",
    ],
    whenYoureDone: "You've completed 10-15 real conversations outside your existing network, written notes after each one, and can point to a specific pattern that showed up more than once — in the interviewees' own words, not your paraphrase of them.",
    whatToDoNext: [
      "If a real, repeated pattern showed up: turn it into a Mission for the next step (often Problem Validation, to check how painful and frequent it really is).",
      "If interviews mostly produced polite, hypothetical answers: that's useful information too — go back to who you're talking to, or reconsider the problem itself, before building anything.",
      "Either way, use Record What I Learned on the related Mission to capture what you found — that's the only step that can update your model.",
    ],
    relatedMissionTypes: ["customer_discovery"],
  },
  {
    slug: "problem-validation",
    title: "Problem Validation",
    description: "How to tell whether a problem is real and painful enough to matter.",
    journeyStage: "start",
    audience: "founder",
    estimatedMinutes: 6,
    relatedPlaybooks: ["customer-discovery", "market-sizing", "mvp"],
    whatIsThis: [
      "Problem validation is the step after customer discovery: deciding, based on what you've actually heard, whether the problem is real, common, and painful enough that people will change behavior — or pay money — to solve it.",
      "A problem can be real without being validated. Plenty of real annoyances aren't painful enough for anyone to do anything about.",
    ],
    whyItMatters: "Investors and your own future self will ask \"why would anyone change what they're doing today?\" A validated problem gives you a real answer. An unvalidated one means you're guessing, and guessing is expensive once you start building.",
    steps: [
      "Write down the problem in one plain sentence, from the customer's point of view, not yours.",
      "Identify what people currently do instead — including \"nothing\" or \"a spreadsheet,\" which are real competitors.",
      "Look for evidence of existing effort: are people already paying for a workaround, cobbling together tools, or complaining publicly?",
      "Ask how often the problem happens and how much time or money it costs when it does.",
      "Separate \"annoying\" from \"painful enough to act on\" — painful problems usually already have some kind of (imperfect) workaround being paid for.",
    ],
    commonMistakes: [
      "Validating that the problem exists, without validating that it's painful enough to pay for.",
      "Assuming a big total market means the problem is validated for your specific first customer.",
      "Confusing your own frustration with a widely-shared one.",
      "Skipping this step because the idea \"obviously\" solves a real problem.",
    ],
    checklist: [
      "You can state the problem in one sentence, from the customer's perspective.",
      "You know what people currently do instead of a solution like yours.",
      "You have evidence people already spend time or money working around this problem.",
      "You can estimate roughly how often and how painfully this problem occurs.",
    ],
    whatGoodLooksLike: "You can point to a specific workaround people already pay for or put effort into today — proof the problem is worth solving, not just worth noticing.",
    objective: "Learn whether the problem is frequent, costly, and urgent enough that someone will actually change behavior — or pay — to fix it.",
    beforeYouStart: [
      "Have your Customer Discovery notes on hand — problem validation works from real conversations you've already had, not fresh guessing.",
      "Write the problem down in one sentence from the customer's point of view, before you look for evidence either way.",
      "Decide who actually owns this problem day-to-day, and separately, who controls the budget that would pay to fix it — they're not always the same person.",
    ],
    questionsToAskOrDo: [
      "How often does this happen — daily, weekly, monthly, rarely?",
      "What do you currently do instead? (Include \"nothing\" and \"a spreadsheet\" as real, valid answers.)",
      "How much time does it cost when it happens? How much money, directly or indirectly?",
      "Has anyone on your team tried to fix or work around this before? What did they try?",
      "What happens if this just never gets solved — what's the actual consequence of doing nothing?",
      "Who would need to say yes to pay for a fix, and who would actually use it day to day?",
    ],
    goodSignal: [
      "The same problem, described independently, comes up across multiple unrelated conversations.",
      "People are already paying for an imperfect workaround (a tool, a consultant, an extra hire) to deal with it.",
      "They describe visible urgency — a deadline, a recurring fire drill, a real cost they can name.",
      "The person you're talking to also controls (or has real influence over) the budget to fix it.",
    ],
    weakSignal: [
      "\"That's interesting\" or \"I could see that being useful\" with no specific example of it happening.",
      "General enthusiasm that isn't tied to anything they've actually done or spent money on.",
      "The problem only comes up when you ask directly — nobody mentions it unprompted.",
      "The person describing the problem has no real ability to pay for or approve a fix.",
    ],
    whenYoureDone: "You can state the problem in one sentence from the customer's perspective, back it with a real workaround people already pay time or money for, and say roughly how often and how painfully it occurs.",
    whatToDoNext: [
      "If the problem looks real and painful: move toward MVP / Prototype Validation to test whether your specific solution actually helps.",
      "If it looks real but not painful enough to act on: that's a legitimate finding — reconsider scope or audience before building.",
      "Use Record What I Learned on the related Mission to capture what you found. This step alone updates your model — reading this playbook does not.",
    ],
    relatedMissionTypes: ["validation"],
  },
  {
    slug: "mvp",
    title: "MVP (Minimum Viable Product)",
    description: "How to build the smallest thing that actually tests your idea.",
    journeyStage: "build",
    audience: "founder",
    estimatedMinutes: 6,
    relatedPlaybooks: ["customer-discovery", "pricing-validation", "early-traction"],
    whatIsThis: [
      "An MVP (minimum viable product) is the smallest version of your product that lets real customers use it and gives you real evidence about whether your idea works — not a stripped-down version of your final vision.",
      "It's a learning tool first, a product second. Its job is to answer your biggest open question as cheaply as possible.",
    ],
    whyItMatters: "Building the \"full\" version before anyone has used anything is the single most common way founders waste months on the wrong features. An MVP forces you to learn from real usage early, when changing course is still cheap.",
    steps: [
      "Identify the single biggest unknown about your idea — usually \"will people actually use/pay for this,\" not \"can we build every feature.\"",
      "Design the smallest thing that tests that specific unknown — sometimes a real (even manual) service before any software at all.",
      "Cut every feature that isn't required to test the core unknown, even ones that feel important.",
      "Get it in front of real users as fast as possible, not a polished version months later.",
      "Decide in advance what result would tell you \"this is working\" versus \"this isn't\" — before you're emotionally invested in the answer.",
    ],
    commonMistakes: [
      "Treating \"MVP\" as an excuse to ship something low-quality with no real test attached to it.",
      "Adding \"just one more feature\" before launching, repeatedly.",
      "Building for scale (thousands of users) before proving anyone wants it at all.",
      "Skipping the step of deciding what success/failure looks like ahead of time.",
    ],
    checklist: [
      "You can name the one specific unknown this version is meant to test.",
      "A stranger could use it without you sitting next to them explaining it.",
      "You defined, in advance, what result would count as a positive signal.",
      "You've cut at least one feature you originally assumed was necessary.",
    ],
    whatGoodLooksLike: "You shipped something small enough to feel a little embarrassed by, and it already answered a real question you couldn't have answered any other way.",
    objective: "Learn whether real users get real value from your specific approach — with the least amount of building possible.",
    beforeYouStart: [
      "Write down the one unknown this test is for, in a single sentence, before building anything.",
      "Decide, in writing, what result would count as \"this works\" versus \"this doesn't\" — before you have a result to be attached to.",
      "Consider whether you need to build software at all yet: a concierge test (you personally deliver the outcome by hand, no product) or a manual/Wizard-of-Oz test (it looks automated, you're doing it manually behind the scenes) often answers the same question faster and cheaper.",
      "Line up a small number of real users willing to actually use it, not just look at it.",
    ],
    questionsToAskOrDo: [
      "Can a stranger complete the core task without you sitting next to them explaining it?",
      "Did they come back and use it again without being asked to?",
      "Where exactly did they hesitate, get confused, or give up?",
      "What did they do that you didn't expect?",
      "Would they be disappointed if this went away? (Ask directly, and watch what they actually do, not just what they say.)",
    ],
    goodSignal: [
      "Users complete the core task on their own, without you explaining or rescuing them.",
      "Some of them come back and use it again without a reminder from you.",
      "They ask when they can use it more, or ask for a specific extension of it.",
      "You learn something real about their behavior you couldn't have predicted from a conversation alone.",
    ],
    weakSignal: [
      "\"This looks cool\" or \"nice idea\" with no actual usage.",
      "People try it once, out of politeness to you, and never come back.",
      "The only usage is you demoing it to them, not them using it themselves.",
      "Validating based on how many features shipped rather than whether anyone got real value.",
    ],
    whenYoureDone: "A stranger has used your smallest possible test on their own, you know whether they got real value from it (not just whether they were polite about it), and you can name a specific, concrete thing you learned.",
    whatToDoNext: [
      "If people got real value and came back: move toward Pricing & Willingness-to-Pay or Early Traction, depending on what you're most uncertain about next.",
      "If they didn't: figure out whether the problem was validated wrong, the approach was wrong, or the test itself was unclear — before building more.",
      "Use Record What I Learned on the related Mission. Building or shipping this test does not, by itself, change anything in your model.",
    ],
    relatedMissionTypes: ["product"],
  },
  {
    slug: "pricing-validation",
    title: "Pricing & Willingness-to-Pay",
    description: "How to find out whether people will actually pay — not just say they would.",
    journeyStage: "build",
    audience: "founder",
    estimatedMinutes: 6,
    relatedPlaybooks: ["problem-validation", "mvp", "pricing"],
    whatIsThis: [
      "Willingness-to-pay validation is testing whether people will actually exchange money for what you're building — not asking them to imagine it hypothetically.",
      "It's different from Business Model & Pricing (deciding your pricing structure once you have a business). This is earlier: finding out if there's real money behind the problem at all.",
    ],
    whyItMatters: "\"Would you pay for this?\" is one of the easiest questions in the world to say yes to, because it costs the person nothing to say yes. The only reliable evidence is what someone does when actually asked to spend money — a price, a deposit, a signature, a card number.",
    steps: [
      "Ask about money they already spend today — on the problem itself, a workaround, or a competing tool — before you mention your own price.",
      "Find out who actually controls the budget, separately from who would use the product day to day.",
      "Propose a real price, even a rough one, instead of asking an open-ended \"what would you pay?\"",
      "Ask for something real: a paid pilot, a deposit, a preorder, a signed (even non-binding) letter of intent — whatever is appropriate at your stage.",
      "Pay attention to price sensitivity: do they negotiate, hesitate, or walk away at a certain number? That tells you more than a yes/no ever will.",
      "Treat an enthusiastic verbal \"yes\" with no money or commitment attached as a weak, not strong, result.",
    ],
    commonMistakes: [
      "Asking \"would you pay $X for this?\" and treating a verbal yes as validated demand.",
      "Never proposing an actual number, so you never learn where real price resistance shows up.",
      "Talking only to the end user when someone else entirely controls the budget.",
      "Treating a free pilot or pure enthusiasm as equivalent to a paid one.",
    ],
    checklist: [
      "You asked about money they already spend on this problem today.",
      "You know who actually controls the budget, not just who would use it.",
      "You proposed a real price rather than asking them to name one.",
      "You asked for something real — payment, a deposit, a signed pilot — not just a verbal opinion.",
    ],
    whatGoodLooksLike: "\"Here's my card, let's start the pilot\" is real evidence. \"I'd probably pay around $50/month\" is a polite guess — useful context, but far weaker, and should never be treated as equivalent.",
    objective: "Learn whether real money — not a hypothetical number — backs up the problem you've validated.",
    beforeYouStart: [
      "Have a rough price in mind before the conversation — you're testing a real number's reaction, not crowdsourcing one.",
      "Decide in advance what a paid pilot, deposit, or preorder would look like for your specific business, so you have something concrete to ask for.",
      "Identify who controls the budget for this purchase, which may not be the person who'd use the product.",
    ],
    questionsToAskOrDo: [
      "What are you currently paying (in money or time) to deal with this today?",
      "Who signs off on a purchase like this at your organization?",
      "Here's roughly what this would cost — what's your first reaction?",
      "Would you be willing to start a paid pilot at that price? What would need to be true first?",
      "Is there a number where this would be an easy yes? Is there one where it's a clear no?",
    ],
    goodSignal: [
      "They agree to pay something now — a deposit, a pilot fee, a preorder — not just a future promise.",
      "They push back and negotiate on price, which means they're seriously considering actually paying.",
      "They can point to an existing budget line or an amount they already spend on this problem.",
      "They ask practical purchase questions (invoicing, contracts, start dates) rather than staying hypothetical.",
    ],
    weakSignal: [
      "\"I'd probably pay around $X/month\" with no actual payment, deposit, or commitment attached.",
      "Enthusiasm about the idea that never turns into a concrete number when you ask.",
      "The person you're talking to has no real authority to approve spending money on this.",
      "They agree to \"look into it internally\" and the conversation quietly ends there.",
    ],
    whenYoureDone: "You've proposed a real price to real potential buyers and gotten either real commitment (money, a deposit, a signed pilot) or a clear, specific reason it's a no — not just a friendly maybe.",
    whatToDoNext: [
      "If you got real commitment: move toward Early Traction / First Customers to turn that into a repeatable process.",
      "If you got polite hesitation: figure out whether it's the price, the problem, or the buyer that's wrong before assuming the whole idea is.",
      "Use Record What I Learned on the related Mission — proposing a price or running a pilot conversation does not, by itself, change your model.",
    ],
    relatedMissionTypes: ["pricing", "economics"],
  },
  {
    slug: "early-traction",
    title: "Early Traction & First Customers",
    description: "How to move from validation into repeatable early customer acquisition.",
    journeyStage: "build",
    audience: "founder",
    estimatedMinutes: 7,
    relatedPlaybooks: ["pricing-validation", "go-to-market", "mvp"],
    whatIsThis: [
      "Early traction is the shift from \"we validated that people want this\" to \"we have a repeatable way to bring on new customers, even a small, manual one.\"",
      "At this stage, it's about proving a process works at a small scale — not about hitting a specific number of users. A narrow channel that reliably brings in a handful of real, engaged customers beats a scattershot approach that produces a lot of noise.",
    ],
    whyItMatters: "Ten customers who actually use your product, keep using it, and can explain why they'd be upset to lose it are stronger evidence than thousands of signups who never come back. Depending on your business, that kind of depth is often more informative than raw signup volume — chasing the wrong number early can hide a real problem instead of revealing it.",
    steps: [
      "Define a narrow initial ideal customer profile (ICP) — specific enough that you could list real people or companies who fit it, not a broad category.",
      "Do founder-led sales/outreach yourself first, even if it doesn't scale — you need to hear objections firsthand before handing this to anyone else.",
      "Pick one acquisition channel to prove first (direct outreach, a specific community, a partnership) rather than spreading thin across many.",
      "Track what actually converts: how many people you reached, how many engaged, how many became real customers.",
      "Put real effort into onboarding and activation — a customer who signs up but never gets to real value doesn't count as traction.",
      "Watch for retention and referrals — customers who stick around and mention you to others are the strongest sign the channel is working.",
    ],
    commonMistakes: [
      "Chasing signup or waitlist counts as if they were proof of a working business, regardless of what your specific model actually needs to prove.",
      "Spreading thin across many acquisition channels at once instead of proving one first.",
      "Neglecting onboarding, so early customers sign up but never actually reach real value.",
      "Assuming a fixed \"good\" traction number exists — the right bar depends heavily on your stage and business model, not a universal benchmark.",
    ],
    checklist: [
      "You can describe your initial ICP specifically enough to name real examples of it.",
      "You've done outreach yourself, not delegated it, for at least your first customers.",
      "You know roughly how many people you reached vs. how many converted, through one channel.",
      "You can name customers who are still actively using it, not just ones who signed up once.",
    ],
    whatGoodLooksLike: "A small number of real customers who are still using the product weeks later, can describe what value they get from it in their own words, and one who mentioned you to someone else without being asked.",
    objective: "Learn whether you have a real, repeatable — even if small and manual — way to bring on customers who stick around.",
    beforeYouStart: [
      "Write down your initial ICP specifically — specific enough that you could name 20 real people or companies who fit it.",
      "Decide on ONE channel to try first, and resist adding a second until the first has a real result.",
      "Set up a simple way to track outreach → engagement → conversion, even a spreadsheet is enough at this stage.",
    ],
    questionsToAskOrDo: [
      "Who exactly are you reaching out to, and why them specifically?",
      "What did you say, and what response did you get?",
      "Did they get to real value, or just sign up and stop?",
      "Are they still using it two or four weeks later?",
      "Would they be upset if it went away? Have they told anyone else about it?",
    ],
    goodSignal: [
      "A small number of customers keep using the product without you prompting them.",
      "You can point to one channel that reliably produces engaged customers, even manually.",
      "A customer mentions you to someone else unprompted, or brings a referral.",
      "Customers can describe, in their own words, the specific value they get.",
    ],
    weakSignal: [
      "A large number of signups with little to no continued usage.",
      "Traction spread thin across many channels with no single one clearly working.",
      "Customers who signed up but never reached the point of real value (no onboarding/activation).",
      "Treating vanity metrics (page views, waitlist size) as if they were proof of a working acquisition channel.",
    ],
    whenYoureDone: "You have a small number of real, engaged customers acquired through a channel you understand, know roughly what it costs to get one, and can describe why they're sticking around in their own words.",
    whatToDoNext: [
      "If a channel is working at small scale: focus on doing more of what's working before adding new channels.",
      "If nothing is sticking: revisit whether the ICP, the channel, or onboarding is the actual bottleneck.",
      "Use Record What I Learned on the related Mission — acquiring customers itself is the real-world action; recording what you learned from it is what can update your model.",
    ],
    relatedMissionTypes: ["gtm"],
  },
  {
    slug: "market-sizing",
    title: "Market & Competition",
    description: "How to size your market honestly and understand who else is solving this.",
    journeyStage: "model",
    audience: "founder",
    estimatedMinutes: 7,
    relatedPlaybooks: ["pricing", "pitch-deck"],
    whatIsThis: [
      "Market sizing is estimating how many potential customers exist and how much revenue they represent. Competitive analysis is understanding who else — including \"doing nothing\" — customers could choose instead of you.",
      "Investors usually care less about the total size of an industry than about the specific, reachable slice of customers you can realistically win first.",
    ],
    whyItMatters: "A market that's too small can't support a venture-scale business. A market that's technically huge but described too broadly (\"the $500B travel industry\") tells an investor you haven't thought about who your actual first customer is.",
    steps: [
      "Start from your specific first customer segment, not the broadest possible category your product could someday touch.",
      "Estimate how many of those specific customers exist, and what they'd realistically pay.",
      "Then show how that beachhead could expand into a larger market over time — the size, then the path to it.",
      "List real alternatives customers use today, including manual workarounds, spreadsheets, and \"nothing\" — these are still competition.",
      "Identify what makes you different in a way that matters to the customer, not just to you.",
    ],
    commonMistakes: [
      "Quoting a huge industry-wide number with no connection to your actual first customer.",
      "Saying \"we have no competitors\" — this almost always signals you haven't looked hard enough, since \"doing nothing\" is always an option.",
      "Confusing a large market with an easy one to enter.",
      "Listing competitors without explaining why customers would choose you over them.",
    ],
    checklist: [
      "You can describe your specific first customer segment and roughly how many exist.",
      "You've shown a believable path from that segment to a larger market.",
      "You've named real alternatives, including manual/DIY ones.",
      "You can say, in one sentence, why a customer would pick you over an alternative.",
    ],
    whatGoodLooksLike: "You can walk someone from \"here's the exact customer we win first\" to \"here's how that expands\" — in that order, not the other way around.",
  },
  {
    slug: "pricing",
    title: "Business Model & Pricing",
    description: "How your company makes money, and how to think about what to charge.",
    journeyStage: "model",
    audience: "founder",
    estimatedMinutes: 7,
    relatedPlaybooks: ["market-sizing", "go-to-market"],
    whatIsThis: [
      "Your business model is the answer to \"how does this become a company that makes more money than it spends?\" Pricing is one part of that: what you charge, whom you charge, and how often.",
      "Common models include one-time purchases, subscriptions, usage-based pricing, commissions/marketplace fees, and advertising — each with very different implications for how you grow.",
    ],
    whyItMatters: "A great product with no credible way to make money isn't a company yet. Investors want to see that you understand the mechanics of your own economics — not that you have the \"correct\" price on day one.",
    steps: [
      "Decide who pays: is it the end user, a business, or a third party (like an advertiser)?",
      "Pick a pricing model that matches how customers get value (per use, per month, per outcome, per transaction).",
      "Estimate a rough price using comparable products, not a number that just feels right.",
      "Estimate your gross margin — what's left after the direct cost of serving a customer — even roughly.",
      "Plan to test and adjust pricing with real customers rather than treating your first number as permanent.",
    ],
    commonMistakes: [
      "Pricing based only on your own costs, without reference to the value delivered.",
      "Being afraid to charge anything, which also removes your best signal of real demand.",
      "Copying a competitor's price without knowing your own margin.",
      "Never revisiting your pricing after initial assumptions turn out wrong.",
    ],
    checklist: [
      "You can state who pays and how often in one sentence.",
      "You have a rough estimate of your gross margin.",
      "Your price is grounded in comparable products or in customer conversations, not a guess.",
      "You have a plan to test pricing with real customers.",
    ],
    whatGoodLooksLike: "You can explain your business model in one breath, and you know roughly what's left over after it costs you to serve one more customer.",
  },
  {
    slug: "go-to-market",
    title: "Go-to-Market",
    description: "How you'll actually get your first customers, and then more of them.",
    journeyStage: "build",
    audience: "founder",
    estimatedMinutes: 6,
    relatedPlaybooks: ["pricing", "customer-discovery"],
    whatIsThis: [
      "Go-to-market (GTM) is your plan for how real customers find out about you, decide to try you, and become paying customers — and how that repeats without you personally doing it by hand forever.",
      "It's different from marketing in general: it's specifically the first, repeatable path to customers, not every possible channel someday.",
    ],
    whyItMatters: "A brilliant product with no distribution plan doesn't grow. Investors want to see one credible, specific first channel — not a list of every marketing channel that exists.",
    steps: [
      "Pick ONE primary channel to start (e.g. direct outreach, a specific community, partnerships, content, paid ads) rather than trying everything at once.",
      "Get your first handful of customers manually, even if it doesn't scale — this teaches you what actually resonates.",
      "Track a simple number: how much does it cost/take to get one customer through this channel?",
      "Look for one thing that's working better than the rest, and do more of that before adding new channels.",
      "Plan how the channel could work with less manual effort over time, once it's proven.",
    ],
    commonMistakes: [
      "Trying five channels at once instead of proving one.",
      "Assuming \"it will go viral\" or \"the app store\" counts as a go-to-market plan.",
      "Never measuring what it actually costs to acquire a customer.",
      "Scaling a channel before confirming it actually works profitably at small scale.",
    ],
    checklist: [
      "You can name your one primary channel and why you picked it.",
      "You've acquired at least a few real customers through it, even manually.",
      "You have a rough sense of what it costs to acquire one customer.",
      "You have a plan for what \"more of what's working\" looks like.",
    ],
    whatGoodLooksLike: "You can point to a specific, repeatable way you got your last few customers — not a hope, a habit.",
  },
  {
    slug: "pitch-deck",
    title: "Pitch Deck",
    description: "How to put together a deck that clearly tells your company's story.",
    journeyStage: "pitch",
    audience: "founder",
    estimatedMinutes: 7,
    relatedPlaybooks: ["fundraising", "market-sizing"],
    whatIsThis: [
      "A pitch deck is a short visual document that tells an investor (or anyone else) what your company does, why it matters, and what you're asking for — clearly enough that someone who's never met you can understand it.",
      "It is not a comprehensive business plan. Its job is to create understanding and interest, not to answer every possible question.",
    ],
    whyItMatters: "A confusing deck creates doubt about the company even when the underlying business is sound. A clear one lets an investor spend their attention evaluating your idea instead of decoding your slides.",
    steps: [
      "Start from the story: what do you do, for whom, and why does it matter — before you worry about slide design.",
      "Cover the essentials: problem, solution, market, business model, traction, team, and your ask — in whatever order tells the clearest story.",
      "Put one idea per slide, and make the headline of each slide the takeaway, not a label.",
      "Back claims with real evidence you actually have — real numbers, real quotes, real pilots — not aspirational language.",
      "Get feedback from people who've never heard your pitch before, and watch where they get confused.",
    ],
    commonMistakes: [
      "Cramming multiple ideas onto one slide.",
      "Describing the market so broadly it doesn't connect to your actual customer.",
      "Leaving out a clear ask — how much you're raising and what it will let you prove.",
      "Treating the deck as the whole pitch instead of a support for the conversation.",
    ],
    checklist: [
      "A stranger can understand what you do from the deck alone, without you narrating.",
      "Every claim is backed by something real you can point to.",
      "The deck states a clear ask: amount and what it will fund.",
      "You've tested it on someone unfamiliar with your company.",
    ],
    whatGoodLooksLike: "Someone who has never met you can read the deck and correctly describe your company back to you in a sentence.",
  },
  {
    slug: "fundraising",
    title: "Fundraising",
    description: "How startup fundraising actually works, in plain terms.",
    journeyStage: "fundraise",
    audience: "founder",
    estimatedMinutes: 8,
    relatedPlaybooks: ["pitch-deck", "cap-table"],
    whatIsThis: [
      "Fundraising is exchanging a piece of ownership in your company for capital, usually to reach a specific next milestone — not free money, and not a requirement for building a company at all.",
      "Common early-stage sources include your own savings, friends and family, angel investors, and venture capital funds, each with different amounts, expectations, and speed.",
    ],
    whyItMatters: "Raising money you don't need, from investors who don't understand your business, or before you can show real evidence, tends to create more problems than it solves. Understanding how the process actually works helps you raise on your own terms, if and when you decide to.",
    steps: [
      "Get clear on why you're raising and what specific milestone the money will let you reach.",
      "Understand your stage's expectations — an idea-stage raise is evaluated very differently from a Series A.",
      "Build a target list of investors who actually invest in your stage and space, not a generic list.",
      "Prepare your story (pitch deck) and your evidence (traction, validation) before you start conversations.",
      "Expect questions, and prepare honest answers for your real weaknesses rather than avoiding them.",
      "Treat a term sheet as the start of negotiation, not a final answer — understand the terms before signing anything.",
    ],
    commonMistakes: [
      "Raising money before you know what specific milestone it's meant to fund.",
      "Pitching investors who don't invest in your stage, sector, or geography.",
      "Avoiding hard questions instead of preparing honest answers for them.",
      "Not understanding basic terms (see the Cap Table & Dilution playbook) before negotiating.",
    ],
    checklist: [
      "You can state, in one sentence, what this specific round of funding is meant to prove or unlock.",
      "You know what evidence investors at your stage typically expect.",
      "You have a real, filtered list of investors who invest in companies like yours.",
      "You understand the basic terms of any offer before you consider signing it.",
    ],
    whatGoodLooksLike: "You can explain exactly what milestone this money buys you, and you'd recognize a bad deal if you saw one.",
  },
  {
    slug: "cap-table",
    title: "Cap Table & Dilution",
    description: "Ownership, dilution, and the basic terms behind a raise, in plain language.",
    journeyStage: "fundraise",
    audience: "founder",
    estimatedMinutes: 9,
    relatedPlaybooks: ["fundraising", "company-formation"],
    whatIsThis: [
      "A cap table (\"capitalization table\") is the record of who owns what percentage of your company — founders, employees, and investors — and how that changes over time.",
      "This playbook explains the core concepts in plain language. It is educational, not individualized legal or financial advice, and the numbers below are simple illustrative examples, not a real cap table.",
    ],
    whyItMatters: "Every fundraising decision changes who owns how much of your company. Understanding these mechanics before you raise money helps you make informed decisions instead of being surprised by them later.",
    steps: [
      "Understand ownership: each shareholder owns a percentage of the total shares outstanding.",
      "Understand dilution: when new shares are issued (usually to a new investor), everyone else's percentage ownership goes down, even though the number of shares they hold doesn't change.",
      "Understand pre-money vs. post-money valuation: pre-money is the company's value before new investment is added; post-money is pre-money plus the new money raised. An investor's ownership percentage is roughly the amount they invest divided by the post-money valuation.",
      "Understand SAFEs: a SAFE (Simple Agreement for Future Equity) is a common early-stage instrument where an investor gives money now in exchange for equity later, usually when a future priced round happens — it is not a loan and not immediate equity.",
      "Understand priced rounds: unlike a SAFE, a priced round sets an actual valuation and issues real equity immediately.",
      "Understand option pools: a block of shares set aside (usually before a raise) to grant to future employees — creating an option pool also dilutes existing shareholders.",
    ],
    commonMistakes: [
      "Confusing a SAFE with a loan — a SAFE has no interest rate or repayment obligation.",
      "Not realizing that a large option pool created right before a raise dilutes the founders, not the incoming investor.",
      "Assuming ownership percentage only changes at a priced round — SAFEs, option pools, and any new share issuance can all dilute existing holders.",
      "Signing multiple SAFEs with inconsistent or unclear terms without understanding how they'll convert together later.",
    ],
    checklist: [
      "You can explain dilution in one sentence, in plain language.",
      "You know the difference between pre-money and post-money valuation.",
      "You understand that a SAFE is not equity yet and not a loan.",
      "You know that an option pool for future hires also dilutes existing shareholders.",
    ],
    whatGoodLooksLike: "Example (illustrative only, not advice): if your company is valued at $4M pre-money and an investor puts in $1M, the post-money valuation is $5M, and that investor owns roughly 1M / 5M = 20% of the company going forward — with everyone else's existing percentage diluted accordingly. You should be able to reconstruct a simple example like this yourself before you raise real money, and to talk to a real lawyer or advisor before you sign anything.",
  },
  {
    slug: "company-formation",
    title: "Company Formation",
    description: "The basics of legally forming a startup, in plain language.",
    journeyStage: "fundraise",
    audience: "founder",
    estimatedMinutes: 6,
    relatedPlaybooks: ["cap-table", "hiring"],
    whatIsThis: [
      "Company formation is legally creating your business as its own entity — most commonly, for a startup planning to raise venture capital in the US, a Delaware C-Corporation.",
      "This is a general educational overview, not legal advice for your specific situation. A real lawyer or formation service should always be involved before you make binding decisions.",
    ],
    whyItMatters: "Forming your company correctly early on avoids expensive fixes later — sorting out ownership, IP, or tax issues after the fact is far harder than setting them up cleanly at the start.",
    steps: [
      "Choose an entity type appropriate for your plans (a Delaware C-Corp is the common default for a venture-fundable startup in the US; other structures fit other situations).",
      "Formalize founder ownership splits and put them in writing early, before it gets emotionally harder to discuss.",
      "Put vesting on founder shares (shares earned gradually over time) so the company isn't stuck if a co-founder leaves early.",
      "Make sure any code, designs, or IP created for the company is legally assigned to the company, not left with an individual.",
      "Get basic agreements in place with any early collaborators before real money or product work is involved.",
    ],
    commonMistakes: [
      "Splitting equity 50/50 without vesting, then facing a messy situation if someone leaves after a month.",
      "Delaying formation so long that a founder's personal assets and the company's finances get mixed together.",
      "Not assigning IP to the company, which can become a serious problem during fundraising or an acquisition.",
      "Making big legal decisions based only on advice from other founders instead of a real lawyer.",
    ],
    checklist: [
      "You've chosen an entity type appropriate to your plans, ideally with professional guidance.",
      "Founder equity is documented and vests over time.",
      "IP created for the company is assigned to the company.",
      "You have (or plan to get) a real lawyer or formation service involved before signing anything binding.",
    ],
    whatGoodLooksLike: "Your founder agreement, equity split, and vesting are all in writing before it would be awkward to bring them up.",
  },
  {
    slug: "hiring",
    title: "Hiring & Team",
    description: "How to think about building your founding and early team.",
    journeyStage: "build",
    audience: "founder",
    estimatedMinutes: 6,
    relatedPlaybooks: ["company-formation", "go-to-market"],
    whatIsThis: [
      "Early hiring is less about filling a formal org chart and more about finding people whose skills cover what the founders can't do themselves, and who can operate with real ownership before there's much process in place.",
      "This includes co-founders, first employees, and early advisors.",
    ],
    whyItMatters: "Investors evaluate teams partly by asking \"why is this specific group of people unusually capable of solving this specific problem?\" Thoughtful early hiring also directly determines what your company can actually build and sell.",
    steps: [
      "Identify the gaps in your founding team's skills honestly — technical, business, domain expertise, or sales.",
      "Prioritize people who can operate with ambiguity and ownership, since early-stage roles rarely have a fixed job description.",
      "Be explicit about equity, vesting, and expectations before someone joins, not after.",
      "Reference-check thoroughly — a bad early hire is disproportionately costly on a small team.",
      "Bring in advisors for specific gaps (e.g. a regulated industry, a technical domain) rather than hiring full-time for a narrow need.",
    ],
    commonMistakes: [
      "Hiring only people similar to the existing founders, leaving real skill gaps uncovered.",
      "Skipping vesting or clear equity terms because \"we trust each other.\"",
      "Hiring too far ahead of actual need, burning cash before it's needed.",
      "Avoiding a hard conversation about a mis-hire for too long on a small team.",
    ],
    checklist: [
      "You can name the specific skill gaps your founding team has today.",
      "Every early team member's equity and vesting terms are clear and in writing.",
      "You've done real reference checks on key early hires.",
      "You've considered an advisor instead of a full-time hire for narrow, specific gaps.",
    ],
    whatGoodLooksLike: "You can explain, for each early hire, the specific gap they filled — not just \"we needed more people.\"",
  },
  {
    slug: "how-vcs-evaluate-startups",
    title: "How VCs Evaluate Startups",
    description: "A plain-language look at how venture investors actually think.",
    journeyStage: "fundraise",
    audience: "general",
    estimatedMinutes: 7,
    relatedPlaybooks: ["fundraising", "cap-table"],
    whatIsThis: [
      "Venture capital funds raise money from their own investors (called limited partners) and invest it into startups, aiming for a small number of investments to grow large enough to make up for the rest that don't work out.",
      "This explains general concepts investors commonly weigh — it is not a formula, not a score, and not a substitute for any individual investor's actual judgment, which varies widely.",
    ],
    whyItMatters: "Understanding the mechanics behind venture investing — not a secret formula, just how the model works — helps you understand why investors ask the questions they do, and why a specific investor might pass on a good business that simply isn't shaped for their fund.",
    steps: [
      "Understand fund economics: a VC fund typically expects most investments to fail or return little, and relies on a small number of large winners to return the whole fund — which is why they generally look for businesses that could become very large, not just profitable.",
      "Understand market: investors often ask whether the market is large enough that even a successful, well-run company could become big enough to matter to their fund's returns.",
      "Understand team: investors are often betting as much on the team's ability to adapt as on the current specific plan, since early-stage plans usually change.",
      "Understand traction: real evidence that customers want something reduces (but never eliminates) the uncertainty in a very early bet.",
      "Understand ownership and return potential: how much of the company an investor gets for their investment, and what would need to happen for that stake to become valuable, matters to the math behind their decision.",
      "Understand risk: every early-stage investment carries a real chance of failure. Investors aren't looking for zero risk — they're looking for risk that's understood and worth taking, for a large enough possible upside.",
    ],
    commonMistakes: [
      "Assuming a \"no\" means your business is bad — it often just means it doesn't fit a specific fund's size, stage, or thesis.",
      "Believing there's a single formula investors apply — real judgment, timing, and fund fit all vary.",
      "Overlooking that investors are also evaluating whether the team can adapt, not only the current plan.",
    ],
    checklist: [
      "You understand roughly why VCs look for large potential outcomes, not just profitable ones.",
      "You understand that a \"no\" is often about fund fit, not a verdict on your business.",
      "You can explain, in plain terms, what \"return potential\" means for an investor.",
    ],
    whatGoodLooksLike: "You can explain why a venture fund's math pushes it toward big, risky bets — without concluding that any single investor's answer is the final word on your company.",
  },
];
